server:
  port: 9527

spring:
  profiles:
    active: ${env}
  application:
    name: randomMeme
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.randommeme.entity